version: "3"

services:
  app:
    container_name: app
    tty: true
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - db
    env_file: .env

  db:
    container_name: db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: peco_password
      MYSQL_DATABASE: peco_db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/db/script:/docker-entrypoint-initdb.d
volumes:
  mysql-data: